### PR TITLE
✨ Added encrypteddev.com to README.md

### PR DESCRIPTION
**Pull request by EncryptedDev**

### CODE REVIEW

**Comment by callumok2004** [comment]
image

**Comment by EncryptedDev** [comment]
Had an issue with Vercel DNS, will fix tonight. Converting this PR to a draft for now

**Comment by heyimnitho** [comment]
Hey there @EncryptedDev, when your website is ready to work, just mention me on #37 for adding your website in my PR too. I'm thinking that Phineas has got so much work to do, so I'm bringing all of the PR's in one PR. Thank you.

**Comment by EncryptedDev** [comment]
Yeah, totally forgot about fixing the DNS. Done now though, should be fine to merge! 👍🏼

**Pull request merged**
