### PR TITLE
add ushie.dev

### PR DESCRIPTION
**Pull request by Ushie**
!!! hi afn

### CODE REVIEW

**Comment by Ushie** [comment]
if possible merge this before others (if there are any PRs made by the time you get to this) so I can be next to afn

**Comment by dustinrouillard** [comment]
I was not able to find any usage of Lanyard on your site, remember this list is only if you use Lanyard in some capacity.

**Comment by Ushie** [comment]
> I was not able to find any usage of Lanyard on your site, remember this list is only if you use Lanyard in some capacity.
> 
> If there is something I'm missing, I'll leave this open so you can fix or let me know if I need to close.

The hero image and the name in the hero title are both via Lanyard, there is also an RPC but I temporarily disabled that for now till I fix mobile responsiveness

**Comment by Ushie** [comment]
oh actually, I just checked the github and I just realised I didn't push those lanyard stuff yet 💀 I guess I kept them as local changes for like over a month, should I mention you when I push it?

**Comment by Ushie** [comment]
@dustinrouillard should be up now

**Pull request merged**
