### PR TITLE
Include discord-status-action

### PR DESCRIPTION
**Pull request by CompeyDev**
Just adding my community repo to the readme (:

### CODE REVIEW

**Comment by dustinrouillard** [comment]
Cool project, however the list of projects just like websites on the readme is first come first serve, you've added your project super high up in the list, you'll need to commit another change moving this to the bottom of the list before it'll be merged.

**Comment by CompeyDev** [comment]
Oops, my bad. I just randomly added it there.

**Comment by CompeyDev** [comment]
Yeah and about the id being hardcoded, thanks for pointing that out, forgot to change that after testing and before committing haha.

**Comment by dustinrouillard** [comment]
Not to be picky now. But you forgot to add the `\` at the end of the line above and remove it off your entry. So it doesn't have a new line.

**Pull request merged**
